import React, {
  createContext,
  useContext,
  useEffect,
  useMemo,
  useState,
} from "react";

const DEFAULT_LANGUAGE = "en";

export const LANGUAGES = [
  { code: "en", label: "English" },
  { code: "am", label: "አማርኛ" },
];

const translations = {
  en: {
    nav: {
      home: "Home",
      rooms: "Rooms",
      services: "Services",
      amenities: "Amenities",
      reviews: "Reviews",
      staff: "Staff",
      bookNow: "Book Now",
    },
    currency: {
      loadingRates: "Loading rates…",
      liveRates: "Live exchange rates",
      estimatedRates: "Estimated rates (server offline)",
    },
    language: {
      english: "English",
      amharic: "አማርኛ",
      switchToEnglish: "Switch to English",
      switchToAmharic: "Switch to Amharic",
    },
    common: {
      checkIn: "Check-in",
      checkOut: "Check-out",
      adults: "Adults",
      children: "Children",
      loading: "Loading…",
      back: "← Back",
      perNight: "/night",
      night: "night",
      nights: "nights",
      total: "Total",
      original: "Original",
      discount: "Discount",
      more: "more",
      floor: "Floor",
      upToGuests: "Up to",
      guests: "guests",
    },
    availability: {
      button: "🔍 Search",
      searching: "Searching…",
      title: "🔍 Check Availability",
      missingDates: "Please select both dates.",
      invalidDateRange: "Check-out must be after check-in.",
      resultsFound: "room available",
      resultsFoundPlural: "rooms available",
      noRoomsFound: "No rooms available for these dates",
      meta: "night",
      metaPlural: "nights",
      hint: "Enter your dates above to see available rooms.",
      backToResults: "← Back to results",
      selectRoom: "Select Room",
      floor: "📍 Floor",
    },
    featured: {
      title: "Our Rooms",
      subtitle: "Handpicked accommodations for your perfect stay",
      viewAll: "View All Rooms →",
      available: "Available",
      unavailable: "Unavailable",
      roomFallback: "Room",
      roomLabel: "Room",
      perNight: "/night",
    },
    roomStatus: {
      available: "Available",
      unavailable: "Unavailable",
      booked: "Booked",
      occupied: "Occupied",
      maintenance: "Maintenance",
    },
    rooms: {
      title: "Our Rooms",
      subtitle: "Browse all",
      subtitleSuffix: "rooms and check availability",
      loading: "Loading rooms…",
      error: "Failed to load rooms. Please try again.",
      filterAll: "All",
      filterAvailable: "Available",
      filterOccupied: "Occupied",
      filterMaintenance: "Maintenance",
      upToGuests: "Up to",
      guests: "guests",
      noRooms: "No",
      noRoomsSuffix: "rooms found.",
      priceNight: "/night",
      writeReview: "Write Review",
      roomNo: "Room",
      floor: "Floor",
      bedType: "Bed",
      roomSize: "Size",
    },
    amenities: {
      title: "Hotel Amenities",
      subtitle: "World-class facilities for an unforgettable stay",
      footerNote1:
        "All amenities are complimentary for hotel guests unless otherwise noted.",
      footerNote2:
        "For more information, please contact our 24-hour concierge.",
      pool: {
        title: "Rooftop Infinity Pool",
        desc: "Heated pool with panoramic city views. Open daily 7 AM – 10 PM.",
      },
      spa: {
        title: "Full-Service Spa",
        desc: "Luxury massages, facials, and wellness therapies.",
      },
      gym: {
        title: "24/7 Fitness Center",
        desc: "State-of-the-art gym with Peloton bikes and personal training.",
      },
      dining: {
        title: "Fine Dining Restaurant",
        desc: "Award-winning cuisine with locally sourced ingredients.",
      },
      bar: {
        title: "Rooftop Bar",
        desc: "Craft cocktails and small plates with stunning sunset views.",
      },
      parking: {
        title: "Valet Parking",
        desc: "Convenient valet service available 24/7 with in-and-out privileges.",
      },
      wifi: {
        title: "High-Speed WiFi",
        desc: "Complimentary gigabit WiFi throughout the hotel and all guest rooms.",
      },
      pet: {
        title: "Pet-Friendly",
        desc: "Your furry friends are welcome! Pet beds, bowls, and treats provided.",
      },
      concierge: {
        title: "24-Hour Concierge",
        desc: "Our dedicated team is available around the clock for any request.",
      },
      business: {
        title: "Business Center",
        desc: "Fully equipped meeting rooms, printing, and secretarial services.",
      },
      garden: {
        title: "Rooftop Garden",
        desc: "Beautiful landscaped gardens for relaxation and outdoor events.",
      },
      shuttle: {
        title: "Airport Shuttle",
        desc: "Complimentary shuttle service to the airport. Advance booking required.",
      },
    },
    booking: {
      title: "Complete Your Booking",
      backToResults: "← Back to results",
      fullName: "Full Name",
      fullNamePlaceholder: "Your full name",
      email: "Email",
      emailOptional: "(optional — used for confirmation only)",
      emailPlaceholder: "your@email.com",
      phone: "Phone",
      phonePlaceholder: "+251 9xx xxx xxx",
      proceedToPayment: "💳 Proceed to Payment",
      processing: "Processing…",
      fillNamePhone: "Please fill in your name and phone.",
      loyaltyChecking: "🔍 Checking loyalty status…",
      loyaltyTitle: "Loyalty Discount Applied!",
      loyaltySub: "You have",
      loyaltySubSuffix: "previous booking",
      loyaltySubSuffixPlural: "previous bookings",
      loyaltyWithUs: "with us",
      adult: "adult",
      adults: "adults",
      child: "child",
      children: "children",
    },
    faq: {
      title: "Frequently Asked Questions",
      subtitle: "Everything you need to know before your stay",
      q1: "What are the check-in and check-out times?",
      a1: "Check-in starts at 3:00 PM and check-out is until 12:00 PM. Early check-in and late check-out are available upon request.",
      q2: "Is breakfast included with the room?",
      a2: "Breakfast is included with Deluxe and Suite bookings. Standard rooms can add breakfast for ETB 500 per person.",
      q3: "What is your cancellation policy?",
      a3: "Free cancellation up to 48 hours before check-in. Cancellations within 48 hours incur one night's charge.",
      q4: "Do you have a pool and spa?",
      a4: "Yes! Our rooftop infinity pool and full-service spa are open daily 7 AM – 10 PM for hotel guests.",
      q5: "Is WiFi available?",
      a5: "Complimentary high-speed gigabit WiFi is available throughout the hotel and all guest rooms.",
      q6: "Do you offer airport transportation?",
      a6: "We offer complimentary shuttle service. Advance booking required at least 24 hours prior.",
      q7: "How can I contact the hotel?",
      a7: "Call us at +251 11 234 5678 or email info@2rnsolomon.com. Our 24-hour front desk is always available.",
    },
    location: {
      title: "Find Us",
      address: "📍 Bole Road, Addis Ababa, Ethiopia",
      frontDesk: "24/7 Front Desk",
      airport: "10 min from Bole Airport",
      bookStay: "Book Your Stay",
    },
    footer: {
      tagline: "Where Luxury Meets Tranquility",
      quickLinks: "Quick Links",
      services: "Services",
      contact: "Contact",
      pool: "Rooftop Pool",
      spa: "Full-Service Spa",
      dining: "Fine Dining",
      shuttle: "Airport Shuttle",
      staffPortal: "🔑 Staff Portal",
      copyright: `© ${new Date().getFullYear()} 2RN Solomon Hotel. All rights reserved.`,
    },
    home: {
      heroTitle: "Welcome to 2RN Solomon",
      heroSubtitle: "Where Luxury Meets Tranquility",
    },
    offer: {
      title: "What We Offer",
      subtitle:
        "Experience exceptional services and facilities designed for your comfort and enjoyment",
      wifiTitle: "Free High-Speed WiFi",
      wifiText: "Stay connected throughout the property",
      spaTitle: "Luxury Spa",
      spaText: "Rejuvenate with world-class treatments",
      gymTitle: "24/7 Gym",
      gymText: "State-of-the-art equipment always open",
      skyBarTitle: "Sky Bar",
      skyBarText: "Craft cocktails with stunning views",
      diningTitle: "Fine Dining",
      diningText: "Award-winning culinary experiences",
    },
    services: {
      title: "Hotel Services",
      subtitle: "Everything you need for a perfect stay — dining, wellness, fitness, and more",
      loading: "Loading hotel services...",
      retry: "Retry",
      noServices: "No services available at the moment. Please check back soon.",
      complimentary: "Complimentary",
      serviceCount: (count) => `service${count !== 1 ? 's' : ''}`,
    },
    menu: {
      sectionTitle: "Restaurant Menu",
      sectionSub: "Fresh ingredients, expertly prepared — dine in or order to your room",
      subMenuTitle: "📋 Available Packages & Pricing",
      free: "Free",
      categories: {
        All: "All",
        Starter: "Starter",
        "Main Course": "Main Course",
        Dessert: "Dessert",
        Drink: "Drink",
        Breakfast: "Breakfast",
        Vegan: "Vegan",
        Special: "Special",
        Massage: "Massage",
        Facial: "Facial",
        "Body Treatment": "Body Treatment",
        Package: "Package",
        Training: "Training",
        Classes: "Classes",
        Pool: "Pool",
        Sauna: "Sauna",
        Airport: "Airport",
        Tours: "Tours",
        "Car Rental": "Car Rental",
        "Meeting Rooms": "Meeting Rooms",
        Conference: "Conference",
        Laundry: "Laundry",
        Parking: "Parking",
        Kids: "Kids",
        Games: "Games",
        Library: "Library",
      },
      items: {
        "Tibs (Ethiopian Sauté)": "Tibs (Ethiopian Sauté)",
        "Injera & Wot Platter": "Injera & Wot Platter",
        "Grilled Nile Perch": "Grilled Nile Perch",
        "Avocado & Tomato Salad": "Avocado & Tomato Salad",
        "Lentil Soup": "Lentil Soup",
        "Macchiato & Pastry": "Macchiato & Pastry",
        "Full English Breakfast": "Full English Breakfast",
        "Mango Juice": "Mango Juice",
        "Chocolate Lava Cake": "Chocolate Lava Cake",
        "Vegan Buddha Bowl": "Vegan Buddha Bowl",
        "Swedish Full-Body Massage": "Swedish Full-Body Massage",
        "Deep Tissue Massage": "Deep Tissue Massage",
        "Luxury Facial Treatment": "Luxury Facial Treatment",
        "Aromatherapy Body Wrap": "Aromatherapy Body Wrap",
        "Couples Spa Package": "Couples Spa Package",
        "Personal Training Session": "Personal Training Session",
        "Guided Yoga Class": "Guided Yoga Class",
        "Pool Lane Reservation": "Pool Lane Reservation",
        "Sauna Session": "Sauna Session",
        "Airport Transfer (One Way)": "Airport Transfer (One Way)",
        "City Sightseeing Tour (Half Day)": "City Sightseeing Tour (Half Day)",
        "Full Day Private Car Hire": "Full Day Private Car Hire",
        "Entoto Hill Day Trip": "Entoto Hill Day Trip",
        "Meeting Room (Half Day)": "Meeting Room (Half Day)",
        "Conference Hall (Full Day)": "Conference Hall (Full Day)",
        "Same-Day Laundry": "Same-Day Laundry",
        "Dry Cleaning (Per Garment)": "Dry Cleaning (Per Garment)",
        "Valet Parking (Per Day)": "Valet Parking (Per Day)",
        "Kids Club (Full Day)": "Kids Club (Full Day)",
        "Billiards & Pool Table (1 Hour)": "Billiards & Pool Table (1 Hour)",
        "Table Tennis (1 Hour)": "Table Tennis (1 Hour)",
        "Library Day Pass": "Library Day Pass",
      },
      descriptions: {
        "Tibs (Ethiopian Sauté)": "Tender beef or lamb cubes sautéed with onions, tomatoes, jalapeños and rosemary.",
        "Injera & Wot Platter": "Traditional spongy injera with doro, misir and gomen wot stews on a large plate.",
        "Grilled Nile Perch": "Fresh Nile perch fillet grilled with spiced rice, vegetables and lemon-herb butter.",
        "Avocado & Tomato Salad": "Creamy avocado, heirloom tomatoes, red onion and herbs in lemon-olive oil dressing.",
        "Lentil Soup": "Slow-cooked red lentils spiced with cumin, turmeric and coriander, with toast.",
        "Macchiato & Pastry": "Freshly pulled Ethiopian macchiato with a flaky croissant or ambasha bread.",
        "Full English Breakfast": "Two eggs any style, grilled sausages, bacon, baked beans, tomato and toast.",
        "Mango Juice": "Freshly squeezed ripe mango juice, no added sugar. Served chilled with a lime wedge.",
        "Chocolate Lava Cake": "Warm dark-chocolate fondant with a molten centre, served with vanilla ice cream.",
        "Vegan Buddha Bowl": "Quinoa, chickpeas, avocado, purple cabbage, edamame and tahini drizzle.",
        "Swedish Full-Body Massage": "Relaxing 60-minute full-body massage using warm oils to relieve tension and stress.",
        "Deep Tissue Massage": "Therapeutic 45-minute massage targeting chronic pain and tight muscles.",
        "Luxury Facial Treatment": "50-minute personalised facial — cleansing, exfoliation and deep hydration.",
        "Aromatherapy Body Wrap": "75-minute body wrap with essential oils to detoxify, soften and rejuvenate skin.",
        "Couples Spa Package": "Two-hour couples retreat — massages, facials and a glass of champagne.",
        "Personal Training Session": "60-minute one-on-one session with a certified personal trainer.",
        "Guided Yoga Class": "45-minute group yoga session for all levels — mat and towel provided.",
        "Pool Lane Reservation": "Reserve a private lane in our 25-metre indoor lap pool for 1 hour.",
        "Sauna Session": "One-hour access to our traditional Finnish sauna with cold plunge pool.",
        "Airport Transfer (One Way)": "Air-conditioned sedan transfer between the hotel and Bole Airport.",
        "City Sightseeing Tour (Half Day)": "Guided 4-hour city tour covering major Addis Ababa landmarks.",
        "Full Day Private Car Hire": "Dedicated driver and vehicle for 8 hours — ideal for business or leisure.",
        "Entoto Hill Day Trip": "Guided full-day excursion to Entoto Natural Park including lunch and entry fees.",
        "Meeting Room (Half Day)": "Air-conditioned room for up to 12 guests with projector, whiteboard and coffee.",
        "Conference Hall (Full Day)": "Large hall for up to 200 delegates — full AV setup, catering available.",
        "Same-Day Laundry": "Wash, dry and fold service — drop off by 9 AM, returned by 6 PM same day.",
        "Dry Cleaning (Per Garment)": "Professional dry cleaning for suits, dresses and delicate garments — ready in 24 hrs.",
        "Valet Parking (Per Day)": "Secure 24-hour valet parking with uniformed attendants — any vehicle size welcome.",
        "Kids Club (Full Day)": "Supervised activities for children aged 4–12 — arts, sports and games.",
        "Billiards & Pool Table (1 Hour)": "Private billiards table in our air-conditioned games lounge — equipment provided.",
        "Table Tennis (1 Hour)": "Dedicated table tennis table — rackets and balls provided for up to 4 players.",
        "Library Day Pass": "Full-day access to our reading lounge with 1,000+ books and quiet booths.",
      },
    },
    gallery: {
      grandLobby: "Grand Lobby",
      diningArea: "Dining Area",
      spaWellness: "Spa & Wellness",
      rooftopBar: "Rooftop Bar",
    },
    payment: {
      title: "Complete Your Payment",
      subtitle: "Follow the steps below to complete your reservation",
      back: "← Back",
      timeRemaining: "Time remaining:",
      timerSub:
        "Complete your payment before time runs out to secure your booking",
      stepDetails: "Details",
      stepPayment: "Payment",
      stepConfirmation: "Confirmation",
      bankDetailsTitle: "🏦 Bank Transfer Details",
      bankName: "Bank Name",
      accountName: "Account Name",
      accountNumber: "Account Number",
      branch: "Branch",
      swiftCode: "SWIFT Code",
      amountLabel: "Amount to Transfer",
      confirmTitle: "📄 Confirm Your Payment",
      screenshotLabel: "Payment Screenshot",
      uploadText: "Click to upload payment screenshot",
      uploadHint: "Upload your bank transfer receipt or payment confirmation",
      removeImage: "Remove image",
      txnRefLabel: "Transaction Reference Number",
      txnRefOptional: "Optional",
      txnRefPlaceholder: "e.g., TXN123456789",
      txnRefHint: "Enter the transaction ID from your bank receipt (optional)",
      infoNote:
        "A payment screenshot is required for verification. You may optionally provide a transaction reference number as well.",
      uploading: "Uploading…",
      confirmButton: "Confirm Payment Details",
      importantNotes: "Important Notes",
      note1: "Your room is held for 5 minutes pending payment verification.",
      note2:
        "Please complete the transfer within this time to secure your booking.",
      note3: "Confirmation email will be sent within 24 hours of verification.",
      note4: "For assistance, contact us at +251 11 234 5678.",
      successTitle: "Payment Proof Submitted!",
      successMsg:
        "Our staff will review your screenshot and confirm your booking shortly.",
      backToHome: "Back to Home",
      errorNoFile: "A payment screenshot is required.",
      errorNoBooking: "Booking ID missing. Please go back and try again.",
      errorUpload: "Upload failed. Please try again.",
      seeBooking: "See booking details",
      copyTitle: "Copy",
    },
    review: {
      title: "Guest Reviews",
      ratingsCount: "reviews",
      ratingLabel: "Rating:",
      poor: "⭐ Poor",
      fair: "⭐⭐ Fair",
      good: "⭐⭐⭐ Good",
      veryGood: "⭐⭐⭐⭐ Very Good",
      excellent: "⭐⭐⭐⭐⭐ Excellent",
      commentLabel: "Comment:",
      commentPlaceholder: "Share your experience (optional)",
      submit: "Submit Review",
      submitting: "Submitting…",
      success: "Review submitted successfully!",
      errorLogin: "Please login to submit a review",
      recentTitle: "Recent Reviews",
      noReviews: "No reviews yet",
      noComment: "No comment",
    },
    login: {
      title: "Login",
      emailPlaceholder: "Email",
      passwordPlaceholder: "Password",
      button: "Login",
      noAccount: "Don't have an account?",
      registerLink: "Register here",
      failed: "Login failed",
    },
    register: {
      title: "Register",
      namePlaceholder: "Full Name",
      emailPlaceholder: "Email",
      passwordPlaceholder: "Password",
      button: "Register",
      success: "Registration successful! Redirecting to login…",
      hasAccount: "Already have an account?",
      loginLink: "Login here",
      failed: "Registration failed",
    },
    analytics: {
      title: "📊 Analytics Dashboard",
      loading: "Loading analytics...",
      fetchFailed: "Failed to fetch analytics",
      totalBookings: "Total Bookings",
      totalRevenue: "Total Revenue",
      occupancyRate: "Occupancy Rate",
      statusBreakdown: "Booking Status Breakdown",
      refresh: "🔄 Refresh Data",
    },
    dashboard: {
      loading: "Loading...",
      loginRequired: "Please login first",
      fetchFailed: "Failed to fetch dashboard data",
      welcome: "Welcome,",
      totalBookings: "Total Bookings",
      activeOffers: "Active Offers",
      occupancyRate: "Occupancy Rate",
      yourBookings: "Your Bookings",
      noBookings: "No bookings yet",
      bookingId: "Booking ID",
      checkIn: "Check-in",
      checkOut: "Check-out",
      totalPrice: "Total Price",
      status: "Status",
    },
    admin: {
      loginTitle: "🔑 Staff Portal",
      loginSubtitle: "Authorized personnel only",
      emailLabel: "Email",
      passwordLabel: "Password",
      emailPlaceholder: "staff@hotel.com",
      loggingIn: "Logging in...",
      login: "Login",
      demoAccounts: "Demo accounts:",
      accessDeniedLogin: "Access denied. Staff only.",
      loginFailed: "Login failed",
      loading: "Loading...",
      dashboardSubtitle: "Booking Management System",
      adminRole: "Admin",
      managerRole: "Manager",
      receptionistRole: "Receptionist",
      dashboard: "Dashboard",
      logout: "↪ Logout",
      totalBookings: "Total Bookings",
      pending: "Pending",
      confirmed: "Confirmed",
      revenue: "Revenue",
      listView: "☰ List View",
      roomManagementTab: "🏨 Room Management",
      repeatCustomersTab: "🔄 Repeat Customers",
      paymentVerificationTab: "💳 Payment Verification",
      offersTab: "🎁 Offers",
      searchPlaceholder: "Search by name, email, or booking ID...",
      allStatus: "All Status",
      checkedIn: "Checked In",
      checkedOut: "Checked Out",
      cancelled: "Cancelled",
      allReception: "All Reception",
      pendingDecision: "Pending Decision",
      approved: "Approved",
      rejected: "Rejected",
      bookingIdCol: "BOOKING ID",
      guestCol: "GUEST",
      roomCol: "ROOM",
      datesCol: "DATES",
      amountCol: "AMOUNT",
      statusCol: "STATUS",
      paymentCol: "PAYMENT",
      receptionCol: "RECEPTION",
      verifiedByCol: "VERIFIED BY",
      actionCol: "ACTION",
      noBookingsFound: "No bookings found matching your criteria.",
      guestFallback: "Guest",
      roomPrefix: "Room",
      paymentPending: "⏳ Pending",
      paymentVerified: "✅ Verified",
      paymentRejected: "❌ Rejected",
      receptionApproved: "✅ Approved",
      receptionRejected: "❌ Rejected",
      receptionPending: "⏳ Pending",
      decide: "⚖️ Decide",
      override: "✏️ Override",
      roomMgmtTitle: "Room Management",
      addNewRoom: "+ Add New Room",
      roomMgmtAccessDenied:
        "Room Management is only available to Admin and Manager.",
      imageCol: "IMAGE",
      roomNumCol: "ROOM #",
      typeCol: "TYPE",
      floorCol: "FLOOR",
      bedCol: "BED",
      maxGuestsCol: "MAX GUESTS",
      sizeCol: "SIZE",
      actionsCol: "ACTIONS",
      editRoomTitle: "Edit Room",
      createRoomTitle: "Create New Room",
      roomNameLabel: "Room Name",
      roomTypeLabel: "Room Type",
      selectType: "Select type",
      priceLabel: "Price/Night (Birr)",
      maxGuestsLabel: "👤 Max Guests",
      roomSizeLabel: "Room Size",
      bedTypeLabel: "🛏 Bed Type",
      descriptionLabel: "Description",
      floorLabel: "Floor",
      statusLabel: "Status",
      amenitiesLabel: "Amenities",
      roomImagesLabel: "Room Images",
      upTo3: "(up to 3)",
      noImagesYet: "No images uploaded yet",
      dropImages: "Drop images here or click to upload",
      slotsRemaining: "slot(s) remaining · JPG, PNG, WebP up to 5MB",
      roomNamePlaceholder: "e.g. Deluxe Ocean Suite",
      pricePlaceholder: "e.g. 2500",
      sizePlaceholder: "42 sqm",
      bedTypePlaceholder: "King, Queen, Twin...",
      descriptionPlaceholder: "Describe the room...",
      floorPlaceholder: "1",
      statusAvailable: "Available",
      statusOccupied: "Occupied",
      statusMaintenance: "Maintenance",
      cancel: "Cancel",
      updateRoom: "Update Room",
      createRoom: "Create Room",
      deleteConfirm: "Delete this room?",
      fetchFailed: "Failed to fetch data",
      verifyFailed: "Failed to verify payment",
      verifyFailedPrefix: "Payment verification failed: ",
      decisionFailed: "Failed to submit decision",
      decisionFailedPrefix: "Decision failed: ",
      deleteRoomFailed: "Failed to delete room",
      saveRoomFailed: "Failed to save room",
      paymentVerificationTitle: "💳 Payment Verification",
      paymentVerifySub: "Review and approve guest payment screenshots",
      awaitingVerification: "⏳ Awaiting Verification",
      noPendingProofs: "No pending payment proofs.",
      bookingPrefix: "Booking #",
      viewFullImage: "View full image",
      approvePayment: "✅ Approve Payment",
      rejectPayment: "❌ Reject",
      verifiedSection: "✅ Verified",
      activeOffers: "Active Offers",
      nameCol: "NAME",
      discountCol: "DISCOUNT",
      validFromCol: "VALID FROM",
      validToCol: "VALID TO",
      repeatCustomersTitle: "🔄 Repeat Customers",
      repeatCustomersSub: "Customers with 2 or more bookings",
      filterByName: "Filter by Name",
      filterByEmail: "Filter by Email",
      filterByPhone: "Filter by Phone",
      namePlaceholder: "Enter customer name...",
      emailFilterPlaceholder: "Enter email address...",
      phoneFilterPlaceholder: "Enter phone number...",
      clearFilters: "Clear Filters",
      customerNameCol: "CUSTOMER NAME",
      emailCol: "EMAIL",
      phoneCol: "PHONE",
      totalBookingsCol: "TOTAL BOOKINGS",
      totalSpentCol: "TOTAL SPENT",
      firstBookingCol: "FIRST BOOKING",
      lastBookingCol: "LAST BOOKING",
      noRepeatCustomers: "No repeat customers found.",
      unknownName: "Unknown",
      naPhone: "N/A",
      repeatCustomersAccessDenied:
        "Repeat Customers view is only available to Admin and Receptionist.",
      overrideDecision: "Override Decision",
      bookingDecision: "Booking Decision",
      guestLabel: "Guest:",
      roomLabel: "Room:",
      datesLabel: "Dates:",
      amountLabel: "Amount:",
      previouslyApprovedBy: "Previously approved by",
      previouslyRejectedBy: "Previously rejected by",
      onDate: "on",
      decisionLabel: "Decision:",
      approveBtn: "✅ Approve",
      rejectBtn: "❌ Reject",
      notesOptional: "Notes (Optional):",
      notesLabel: "Notes:",
      notesPlaceholder: "Add any additional notes...",
      submitting: "Submitting...",
      submitDecision: "Submit Decision",
      loyaltyDiscount: "loyalty",
      loyaltyDiscountApplied: "loyalty discount was applied",
      accessDeniedTitle: "Access Denied",
    },
  },

  am: {
    nav: {
      home: "መነሻ",
      rooms: "ክፍሎች",
      services: "አገልግሎቶች",
      amenities: "አገልግሎቶች",
      reviews: "ግምገማዎች",
      staff: "ሰራተኞች",
      bookNow: "አሁን ያስይዙ",
    },
    currency: {
      loadingRates: "ተመኖች በመጫን ላይ…",
      liveRates: "የቀጥታ ምንዛሬ ተመኖች",
      estimatedRates: "ግምታዊ ተመኖች (ሰርቨሩ ከመስመር ውጭ ነው)",
    },
    language: {
      english: "English",
      amharic: "አማርኛ",
      switchToEnglish: "ወደ English ቀይር",
      switchToAmharic: "ወደ አማርኛ ቀይር",
    },
    common: {
      checkIn: "ቀን መግቢያ",
      checkOut: "ቀን መውጫ",
      adults: "ጎልማሶች",
      children: "ልጆች",
      loading: "በመጫን ላይ…",
      back: "← ወደኋላ",
      perNight: "/ሌሊት",
      night: "ሌሊት",
      nights: "ሌሊቶች",
      total: "ጠቅላላ",
      original: "መጀመሪያ",
      discount: "ቅናሽ",
      more: "ተጨማሪ",
      floor: "ፎቅ",
      upToGuests: "እስከ",
      guests: "እንግዶች",
    },
    availability: {
      button: "🔍 ፈልግ",
      searching: "በፍለጋ ላይ…",
      title: "🔍 ክፍት ቀናት ፈልግ",
      missingDates: "እባክዎ ሁለቱንም ቀናት ይምረጡ።",
      invalidDateRange: "መውጫ ቀን ከመግቢያ ቀን በኋላ መሆን አለበት።",
      resultsFound: "ክፍል ይገኛል",
      resultsFoundPlural: "ክፍሎች ይገኛሉ",
      noRoomsFound: "ለእነዚህ ቀናት ምንም ክፍል አልተገኘም",
      meta: "ሌሊት",
      metaPlural: "ሌሊቶች",
      hint: "ክፍት ክፍሎችን ለማየት ቀናትዎን ከላይ ያስገቡ።",
      backToResults: "← ወደ ውጤቶቹ ተመለስ",
      selectRoom: "ክፍሉን ይምረጡ",
      floor: "📍 ፎቅ",
    },
    featured: {
      title: "የእኛ ክፍሎች",
      subtitle: "ለፍጹም ቆይታዎ የተመረጡ መኖሪያዎች",
      viewAll: "ሁሉንም ክፍሎች ይመልከቱ →",
      available: "ይገኛል",
      unavailable: "አይገኝም",
      roomFallback: "ክፍል",
      roomLabel: "ክፍል",
      perNight: "/ሌሊት",
    },
    roomStatus: {
      available: "ይገኛል",
      unavailable: "አይገኝም",
      booked: "ተይዟል",
      occupied: "ተይዟል",
      maintenance: "ጥገና ላይ",
    },
    rooms: {
      title: "የእኛ ክፍሎች",
      subtitle: "ሁሉንም",
      subtitleSuffix: "ክፍሎች ያስሱ እና ተገኝነት ያረጋግጡ",
      loading: "ክፍሎች በመጫን ላይ…",
      error: "ክፍሎችን መጫን አልተቻለም። እንደገና ይሞክሩ።",
      filterAll: "ሁሉም",
      filterAvailable: "ያሉ",
      filterOccupied: "የተያዙ",
      filterMaintenance: "ጥገና ላይ",
      upToGuests: "እስከ",
      guests: "እንግዶች",
      noRooms: "ምንም",
      noRoomsSuffix: "ክፍሎች አልተገኙም።",
      priceNight: "/ሌሊት",
      writeReview: "ግምገሽ ይጻፉ",
      roomNo: "ክፍል",
      floor: "ፎቅ",
      bedType: "አልጋ",
      roomSize: "ስፋት",
    },
    amenities: {
      title: "የሆቴሉ አገልግሎቶች",
      subtitle: "ለማይረሳ ቆይታ የዓለም ደረጃ መገልገያዎች",
      footerNote1: "ሁሉም አገልግሎቶች ለሆቴሉ እንግዶች ያለምክር ናቸው (ካልተገለጸ በስተቀር)።",
      footerNote2: "ለበለጠ መረጃ እባክዎ 24 ሰዓት ሁሉ ካለውን አስተናጋጃ ቡድን ያነጋግሩ።",
      pool: {
        title: "ጣሪያ ላይ ያለ ኢንፊኒቲ ፑል",
        desc: "ሙቅ ፑል ከሰፊ የከተማ እይታ ጋር። ዕለት ዕለት ከጠዋቱ 7 እስከ ምሽቱ 10 ክፍት ነው።",
      },
      spa: { title: "ሙሉ አገልግሎት ስፓ", desc: "ቅንጦት ማሳጅ፣ ፊት ሕክምናና የጤና ሕክምናዎች።" },
      gym: {
        title: "24/7 የስፖርት ማዕከል",
        desc: "ዘመናዊ መሳሪያዎች ያሉት ጂም — ሁልጊዜ ክፍት ነው።",
      },
      dining: { title: "ምርጥ ምግብ ቤት", desc: "ሽልማት ያገኘ ምግብ ከአካባቢ ምርቶች የሚዘጋጅ።" },
      bar: {
        title: "ጣሪያ ላይ ባር",
        desc: "የተዘጋጀ ኮክቴልና ምግብ ከሚያማምር የፀሐይ ስምጥ እይታ ጋር።",
      },
      parking: {
        title: "ቫሌ ፓርኪንግ",
        desc: "24 ሰዓት ሁሉ ያለ ቫሌ አገልግሎት — ወደ ፓርኪንግ ወጪ ቅናሽ አለ።",
      },
      wifi: {
        title: "ፈጣን WiFi",
        desc: "ለሆቴሉ እንግዶች በሙሉ ሆቴሉ ውስጥ ያለ ነጻ ጊጋቢት WiFi።",
      },
      pet: {
        title: "የቤት እንስሳ ተቀባይ",
        desc: "የሚወዷቸው ቤት እንስሳዎቻቸው ተቀባይ ናቸው! የእንስሳ አልጋ፣ ሳህን እና ምግብ ይቀርባል።",
      },
      concierge: {
        title: "24 ሰዓት አስተናጋጅ",
        desc: "ቡድናችን ለማንኛውም ጥያቄ ሁልጊዜ ዝግጁ ነው።",
      },
      business: {
        title: "የሥራ ማዕከል",
        desc: "ሙሉ ስብሰባ ክፍሎች፣ ማተሚያ እና ፀሐፊ አገልግሎቶች።",
      },
      garden: {
        title: "ጣሪያ ላይ የአትክልት ቦታ",
        desc: "ለዘና ወይም ለዝግጅቶች ያለ ቆንጆ የዛፍ አካባቢ።",
      },
      shuttle: {
        title: "የአውሮፕላን ማረፊያ ሸዴ",
        desc: "ወደ አውሮፕላን ማረፊያ ያለ ነጻ ሸዴ። አስቀድሞ ቦታ ማስያዝ ይጠይቃል።",
      },
    },
    booking: {
      title: "ቦታ ማስያዝዎን ያጠናቅቁ",
      backToResults: "← ወደ ውጤቶቹ ተመለስ",
      fullName: "ሙሉ ስም",
      fullNamePlaceholder: "ሙሉ ስምዎ",
      email: "ኢሜይል",
      emailOptional: "(አማራጭ — ለማረጋገጫ ብቻ ያገለግላል)",
      emailPlaceholder: "your@email.com",
      phone: "ስልክ",
      phonePlaceholder: "+251 9xx xxx xxx",
      proceedToPayment: "💳 ወደ ክፍያ ቀጥሉ",
      processing: "በሂደት ላይ…",
      fillNamePhone: "እባክዎ ስምዎን እና ስልክዎን ያስገቡ።",
      loyaltyChecking: "🔍 የታማኝነት ደረጃዎን በማረጋገጥ ላይ…",
      loyaltyTitle: "የታማኝነት ቅናሽ ተተግብሯል!",
      loyaltySub: "ዉይ አለዎት",
      loyaltySubSuffix: "ቀዳሚ ቦታ ማስያዝ",
      loyaltySubSuffixPlural: "ቀዳሚ ቦታ ማስያዞች",
      loyaltyWithUs: "ከእኛ ጋር",
      adult: "ጎልማሳ",
      adults: "ጎልማሶች",
      child: "ልጅ",
      children: "ልጆች",
    },
    faq: {
      title: "ተደጋጋሚ ጥያቄዎች",
      subtitle: "ቆይታዎ ከመጀመሩ በፊት ሁሉንም ነገር ያውቁ",
      q1: "ቀን መግቢያ እና ቀን መውጫ ሰዓቶች ምንን ናቸው?",
      a1: "ቀን መግቢያ ከሰዓት 3:00 ጀምሮ ሲሆን ቀን መውጫ እስከ ምሽቱ 12:00 ነው። ቀደም ብሎ መግባትና ዘግይቶ መውጣት በጥያቄ ይቻላል።",
      q2: "ቁርስ ከክፍሉ ዋጋ ጋር ይካተታል?",
      a2: "ቁርስ ለዴሉክስ እና ሱዊት ክፍሎች ይካተታል። ደረጃ ያላቸው ክፍሎች ቁርስ ለአንድ ሰው ETB 500 ብር ሊጨምሩ ይችላሉ።",
      q3: "የስረዛ ፖሊሲዎ ምንድን ነው?",
      a3: "ቀን መግቢያ ከ48 ሰዓት በፊት ያለ ክፍያ ሰርዞ ይቻላል። ከ48 ሰዓት ውስጥ ሲሰረዝ የአንድ ሌሊት ክፍያ ያስከፍላል።",
      q4: "ፑልና ስፓ አለዎት?",
      a4: "አዎ! የጣሪያ ኢንፊኒቲ ፑልና ሙሉ አገልግሎት ስፓ ለሆቴሉ እንግዶች ዕለት ዕለት ከጠዋቱ 7 እስከ ምሽቱ 10 ክፍት ናቸው።",
      q5: "WiFi አለ?",
      a5: "ያለ ምክር ፈጣን ጊጋቢት WiFi በሙሉ ሆቴሉ እና ሁሉም የእንግዳ ክፍሎች ውስጥ ይገኛል።",
      q6: "የአውሮፕላን ማረፊያ መጓጓዣ ይሰጣሉ?",
      a6: "ነጻ ሸዴ አገልግሎት እናቀርባለን። ቢያንስ 24 ሰዓት አስቀድሞ ቦታ ማስያዝ ያስፈልጋል።",
      q7: "ሆቴሉን እንዴት ማነጋገር ይችላሉ?",
      a7: "በ+251 11 234 5678 ደውሉ ወይም info@2rnsolomon.com ኢሜይል ያድርጉ። 24 ሰዓት ያለ ሎቢ ሁልጊዜ ዝግጁ ነው።",
    },
    location: {
      title: "ያገኙናል",
      address: "📍 ቦሌ መንገድ፣ አዲስ አበባ፣ ኢትዮጵያ",
      frontDesk: "24/7 የፊት ዴስክ",
      airport: "ከቦሌ አውሮፕላን ማረፊያ 10 ደቂቃ ርቀት",
      bookStay: "ቆይታዎን ያስይዙ",
    },
    footer: {
      tagline: "ቅንጦትና ሰላም የሚገናኙበት",
      quickLinks: "ፈጣን ማስፈንጠሪያዎች",
      services: "አገልግሎቶች",
      contact: "ያነጋግሩን",
      pool: "ጣሪያ ፑል",
      spa: "ሙሉ ስፓ",
      dining: "ምርጥ ምግብ ቤት",
      shuttle: "የአውሮፕላን ሸዴ",
      staffPortal: "🔑 የሰራተኞች መግቢያ",
      copyright: `© ${new Date().getFullYear()} 2RN Solomon Hotel. መብቱ በሕግ የተጠበቀ ነው።`,
    },
    home: {
      heroTitle: "እንኳን ወደ 2RN Solomon በደህና መጡ",
      heroSubtitle: "ቅንጦትና ሰላም የሚገናኙበት",
    },
    offer: {
      title: "የምናቀርበው",
      subtitle: "ለምቾትዎ እና ለመዝናኛዎ የተዘጋጁ ልዩ አገልግሎቶችና መገልገያዎች",
      wifiTitle: "ፈጣን ነጻ WiFi",
      wifiText: "በሙሉ ንብረቱ ውስጥ ይገናኙ",
      spaTitle: "የቅንጦት ስፓ",
      spaText: "በዓለም ደረጃ ሕክምናዎች ይዝናኑ",
      gymTitle: "24/7 ጂም",
      gymText: "ዘመናዊ መሳሪያዎች ሁልጊዜ ክፍት ናቸው",
      skyBarTitle: "Sky Bar",
      skyBarText: "አስደናቂ እይታዎች ጋር የተዘጋጀ ኮክቴል",
      diningTitle: "ከፍተኛ የምግብ አገልግሎት",
      diningText: "ሽልማት ያገኙ የምግብ ልምዶች",
    },
    services: {
      title: "የሆቴሉ አገልግሎቶች",
      subtitle: "ለፍጹም ቆይታ የሚያስፈልግ ሁሉም ነገር — ምግብ፣ ደህንነት፣ ስፖርት እና ሌሎችም",
      loading: "የሆቴሉ አገልግሎቶች በመጫን ላይ...",
      retry: "እንደገና ይሞክሩ",
      noServices: "በአሁኑ ጊዜ ምንም አገልግሎት የለም። እባክዎ ቆይተው ይመለከቱ።",
      complimentary: "ነጻ",
      serviceCount: (count) => `አገልግሎት${count !== 1 ? 'ች' : ''}`,
    },
    menu: {
      sectionTitle: "የምግብ ቤት ዝርዝር",
      sectionSub: "ትኩስ ምርቶችን ተጠቅሞ በሙያ የሚዘጋጅ — ምግብ ቤት ወይም ወደ ክፍልዎ ያዙ",
      subMenuTitle: "📋 ያሉ አቅርቦቶችና ዋጋ",
      free: "ነጻ",
      categories: {
        All: "ሁሉም",
        Starter: "ቀዳሚ ምግብ",
        "Main Course": "ዋና ምግብ",
        Dessert: "ጣፋጭ",
        Drink: "መጠጥ",
        Breakfast: "ቁርስ",
        Vegan: "ቬጋን",
        Special: "ልዩ",
        Massage: "ማሳጅ",
        Facial: "የፊት ሕክምና",
        "Body Treatment": "የሰውነት ሕክምና",
        Package: "ፓኬጅ",
        Training: "ስልጠና",
        Classes: "ክፍለ ጊዜ",
        Pool: "ፑል",
        Sauna: "ሳውና",
        Airport: "አውሮፕላን ማረፊያ",
        Tours: "ጉዞ",
        "Car Rental": "መኪና ኪራይ",
        "Meeting Rooms": "የስብሰባ ክፍሎች",
        Conference: "ኮንፈረንስ",
        Laundry: "ልብስ ማጠቢያ",
        Parking: "ፓርኪንግ",
        Kids: "ልጆች",
        Games: "ጨዋታ",
        Library: "ቤተ መጽሐፍት",
      },
      items: {
        "Tibs (Ethiopian Sauté)": "ጥብስ (የኢትዮጵያ ጥብስ)",
        "Injera & Wot Platter": "እንጀራ እና ወጥ",
        "Grilled Nile Perch": "የተጠበሰ ዓሳ",
        "Avocado & Tomato Salad": "አቮካዶ እና ቲማቲም ሰላጣ",
        "Lentil Soup": "የምስር ሾርባ",
        "Macchiato & Pastry": "ማኪያቶ እና ዳቦ",
        "Full English Breakfast": "ሙሉ እንግሊዝኛ ቁርስ",
        "Mango Juice": "የማንጎ ጭማቂ",
        "Chocolate Lava Cake": "ቾኮሌት ኬክ",
        "Vegan Buddha Bowl": "የቬጋን ሰሃን",
        "Swedish Full-Body Massage": "የሙሉ ሰውነት ማሳጅ",
        "Deep Tissue Massage": "ጥልቅ ማሳጅ",
        "Luxury Facial Treatment": "የቅንጦት የፊት ሕክምና",
        "Aromatherapy Body Wrap": "አሮማቴራፒ የሰውነት ሕክምና",
        "Couples Spa Package": "የጥንዶች ስፓ ፓኬጅ",
        "Personal Training Session": "የግል ስልጠና",
        "Guided Yoga Class": "የዮጋ ክፍለ ጊዜ",
        "Pool Lane Reservation": "የፑል መስመር ቦታ ማስያዝ",
        "Sauna Session": "ሳውና አገልግሎት",
        "Airport Transfer (One Way)": "የአውሮፕላን ማረፊያ ትራንስፈር (አንድ አቅጣጫ)",
        "City Sightseeing Tour (Half Day)": "የከተማ ጉዞ (ግማሽ ቀን)",
        "Full Day Private Car Hire": "ሙሉ ቀን የግል መኪና ኪራይ",
        "Entoto Hill Day Trip": "ወደ ኢንቶቶ ኮረብታ ጉዞ",
        "Meeting Room (Half Day)": "የስብሰባ ክፍል (ግማሽ ቀን)",
        "Conference Hall (Full Day)": "የኮንፈረንስ አዳራሽ (ሙሉ ቀን)",
        "Same-Day Laundry": "በዕለቱ ልብስ ማጠቢያ",
        "Dry Cleaning (Per Garment)": "ደረቅ ልብስ ማጠቢያ (በልብስ)",
        "Valet Parking (Per Day)": "ቫሌ ፓርኪንግ (በቀን)",
        "Kids Club (Full Day)": "የህጻናት ክለብ (ሙሉ ቀን)",
        "Billiards & Pool Table (1 Hour)": "ቢሊያርድ (1 ሰዓት)",
        "Table Tennis (1 Hour)": "ቴብል ቴኒስ (1 ሰዓት)",
        "Library Day Pass": "የቤተ መጽሐፍት ቀን ፓስ",
      },
      descriptions: {
        "Tibs (Ethiopian Sauté)": "ሽንኩርት፣ ቲማቲም፣ ቀይ ሚጥሚጣ እና ሮዝሜሪ ጋር የተጠበሰ ለስላሳ የበሬ ወይም የበግ ስጋ።",
        "Injera & Wot Platter": "በዋና ሰሃን ላይ ዶሮ፣ ምስር እና ጎመን ወጥ ጋር የሚቀርብ ባህላዊ እንጀራ።",
        "Grilled Nile Perch": "የቅባት ሩዝ፣ አትክልትና ሎሚ-ቅቤ ሶስ ጋር የሚቀርብ የተጠበሰ ዓሳ።",
        "Avocado & Tomato Salad": "ክሬሚ አቮካዶ፣ ቲማቲም፣ ቀይ ሽንኩርትና ቅጠላቅጠሎች በሎሚ ዘይት ፈሰስ።",
        "Lentil Soup": "ቅርፍት ሱፍ፣ ቢጫ ዱቄት እና ኮሪያንደር ጋር የሚዘጋጅ ቀስ ብሎ የሚቀቀል ቀይ ምስር፣ ከጠቅ ዳቦ ጋር።",
        "Macchiato & Pastry": "ትኩስ የኢትዮጵያ ማኪያቶ ከብስኩት ክሮሳን ወይም ባህላዊ አምባሻ ጋር።",
        "Full English Breakfast": "ሁለት እንቁላል፣ ሙቅ ሶሲስ፣ ቤከን፣ ባቄላ፣ ቲማቲምና ጠቅ ዳቦ።",
        "Mango Juice": "ስኳር ሳይጨምር፣ ውሃ ሳይበዘበዝ የሚዘጋጅ ትኩስ የማንጎ ጭማቂ። ቀዝቃዛ ሆኖ ይቀርባል።",
        "Chocolate Lava Cake": "ሙቅ ቾኮሌት ኬክ ከቫኒላ አይስ ክሪም ጋር ይቀርባል።",
        "Vegan Buddha Bowl": "ኩዊኖዋ፣ ጥብስ ሽምብራ፣ አቮካዶ፣ ሐምራዊ ጎመን፣ ኤዳሜሜ እና ታሂኒ ፈሰስ።",
        "Swedish Full-Body Massage": "ጡንቻ ድካምና ውጥረት ለማስታረቅ ሙቅ ዘይት ተጠቅሞ 60 ደቂቃ ሙሉ ሰውነት ማሳጅ።",
        "Deep Tissue Massage": "ለረዥም ጊዜ ህመምና ጠንካራ ጡንቻዎች ያነጣጠረ 45 ደቂቃ ሕክምናዊ ማሳጅ።",
        "Luxury Facial Treatment": "50 ደቂቃ ግላዊ የፊት ሕክምና — ማጽዳት፣ ቆዳ ማለሳለስ እና ጥልቅ እርጥበት ማስጠጣት።",
        "Aromatherapy Body Wrap": "ቆዳን ለማጽዳት፣ ለማለሳለስ እና ለማደስ ዋነኛ ዘይቶች ጥቅም ላይ የሚውልበት 75 ደቂቃ የሰውነት ሕክምና።",
        "Couples Spa Package": "ጎን ለጎን ማሳጅ፣ ፊት ሕክምናና ሻምፓኝ ያካተተ 2 ሰዓት የጥንዶች ዕረፍት ጊዜ።",
        "Personal Training Session": "የምስክር ወረቀት ካለው ግላዊ አሰልጣኝ ጋር 60 ደቂቃ ልዩ የአካል ብቃት ስልጠና።",
        "Guided Yoga Class": "ለሁሉም ደረጃ 45 ደቂቃ የቡድን ዮጋ ክፍለ ጊዜ — ምንጣፍና ፎጣ ይቀርባል።",
        "Pool Lane Reservation": "ለ1 ሰዓት በ25 ሜትር ውስጠ ፑላችን ውስጥ የግል ሌን ቦታ ማስያዝ።",
        "Sauna Session": "ቀዝቃዛ ጋን ጋር በሆነ ባህላዊ ፊንላንዳዊ ሳውናችን ውስጥ 1 ሰዓት ቆይታ።",
        "Airport Transfer (One Way)": "ከሆቴሉ ወደ ቦሌ አውሮፕላን ማረፊያ ወይም ተቃራኒ አቅጣጫ ሚዛናዊ ትራንስፈር።",
        "City Sightseeing Tour (Half Day)": "ዋና ዋና የአዲስ አበባ መስህቦችን የሚዳስስ 4 ሰዓት ጉዞ።",
        "Full Day Private Car Hire": "ለሥራ ወይም ለዝናና ጊዜ 8 ሰዓት ያለ ሹፌርና መኪና ኪራይ።",
        "Entoto Hill Day Trip": "ምሳና ክፍያ ጨምሮ ወደ ኢንቶቶ ናቹራል ፓርክ ሙሉ ቀን ጉዞ።",
        "Meeting Room (Half Day)": "ፕሮጀክተር፣ ሩፍ ቦርድና ቡና ያካተተ እስከ 12 ሰዎች የሚስተናገድ ስብሰባ ክፍል።",
        "Conference Hall (Full Day)": "ሙሉ የAV ዝግጅት፣ ምግብ አቅርቦት ይቻላልና እስከ 200 ተሳታፊ ያለ ኮንፈረንስ አዳራሽ።",
        "Same-Day Laundry": "ከጠዋቱ 9 ሰዓት ቢቀርብ ምሽቱ 6 ሰዓት ይረከባሉ — ሙሉ አገልግሎት።",
        "Dry Cleaning (Per Garment)": "ለሱፍ፣ ቀሚስና ስስ ልብሶች ሙያዊ ደረቅ ማጠቢያ — በ24 ሰዓት ዝግጁ።",
        "Valet Parking (Per Day)": "ሁሉም ዓይነት መኪና ተቀባይ — 24 ሰዓት ዘበኛ ቫሌ ፓርኪንግ አገልግሎት።",
        "Kids Club (Full Day)": "ለ4-12 ዓመት ህጻናት ጥበብ፣ ስፖርትና ጨዋታ ያካተተ ቁጥጥር ያለው ቀናቱ ሙሉ ፕሮግራም።",
        "Billiards & Pool Table (1 Hour)": "በኤ.ሲ ክፍላቸን ያለ ቢሊያርድ ጠረጴዛ ብቻዊ አጠቃቀም — ሁሉም መሳሪያ ይቀርባል።",
        "Table Tennis (1 Hour)": "እስከ 4 ተጫዋቾች ፊሽካና ኳስ ጨምሮ ዝግጁ የቴብል ቴኒስ ጠረጴዛ።",
        "Library Day Pass": "ከ1,000 በላይ መጻሕፍት፣ ጋዜጦችና ፀጥተኛ ቡዝ ያሉበት ማንበቢያ ሳሎናችን ሙሉ ቀን።",
      },
    },
    gallery: {
      grandLobby: "ዋና መቀበያ አዳራሽ",
      diningArea: "የመመገቢያ ቦታ",
      spaWellness: "ስፓ እና ደህንነት",
      rooftopBar: "የላይኛው ባር",
    },
    payment: {
      title: "ክፍያዎን ያጠናቅቁ",
      subtitle: "ቦታ ማስያዝዎን ለማጠናቀቅ ከዚህ በታች ያሉትን ደረጃዎች ይከተሉ",
      back: "← ወደኋላ",
      timeRemaining: "ቀሪ ጊዜ:",
      timerSub: "ቦታ ማስያዝዎን ለማረጋገጥ ጊዜው ከማለፉ በፊት ክፍያዎን ያጠናቅቁ",
      stepDetails: "ዝርዝር",
      stepPayment: "ክፍያ",
      stepConfirmation: "ማረጋገጫ",
      bankDetailsTitle: "🏦 የባንክ ዝውውር ዝርዝሮች",
      bankName: "የባንክ ስም",
      accountName: "የሒሳብ ስም",
      accountNumber: "የሒሳብ ቁጥር",
      branch: "ቅርንጫፍ",
      swiftCode: "SWIFT ኮድ",
      amountLabel: "ማስተላለፍ ያለብዎት ገንዘብ",
      confirmTitle: "📄 ክፍያዎን ያረጋግጡ",
      screenshotLabel: "የክፍያ ቅጽበታዊ ገጽ",
      uploadText: "ቅጽበታዊ ገጽ ለመጫን ይጫኑ",
      uploadHint: "የባንክ ዝውውር ደረሰኝ ወይም የክፍያ ማረጋገጫ ይጫኑ",
      removeImage: "ምስሉን አስወግድ",
      txnRefLabel: "የግብይት ማጣቀሻ ቁጥር",
      txnRefOptional: "አማራጭ",
      txnRefPlaceholder: "ለምሳሌ: TXN123456789",
      txnRefHint: "ከባንክ ደረሰኝዎ የግብይት መለያ ቁጥር ያስገቡ (አማራጭ)",
      infoNote:
        "ለማረጋገጫ የክፍያ ቅጽበታዊ ገጽ ያስፈልጋል። አማራጭ የሆነ የግብይት ማጣቀሻ ቁጥርም ማቅረብ ይችላሉ።",
      uploading: "በመጫን ላይ…",
      confirmButton: "የክፍያ ዝርዝሮችን ያረጋግጡ",
      importantNotes: "አስፈላጊ ማሳሰቢያዎች",
      note1: "ክፍያ ሲረጋገጥ ክፍልዎ ለ5 ደቂቃ ይያዛል።",
      note2: "ቦታ ማስያዝዎን ለማረጋገጥ ዝውውሩን ውስጥ ያጠናቅቁ።",
      note3: "ከተረጋገጠ ከ24 ሰዓት ውስጥ ማረጋገጫ ኢሜይል ይላካል።",
      note4: "ለእርዳታ +251 11 234 5678 ያነጋግሩን።",
      successTitle: "የክፍያ ማስረጃ ቀርቧል!",
      successMsg: "ሰራተኞቻችን ቅጽበታዊ ገጽዎን ይፈትሹና ቦታ ማስያዝዎን በቅርቡ ያረጋግጣሉ።",
      backToHome: "ወደ መነሻ ተመለስ",
      errorNoFile: "የክፍያ ቅጽበታዊ ገጽ ያስፈልጋል።",
      errorNoBooking: "የቦታ ማስያዝ መለያ ጠፍቷል። ወደኋላ ተመልሰው እንደገና ይሞክሩ።",
      errorUpload: "መጫን አልተሳካም። እንደገና ይሞክሩ።",
      seeBooking: "የቦታ ማስያዝ ዝርዝር ይመልከቱ",
      copyTitle: "ቅዳ",
    },
    review: {
      title: "የእንግዳ ግምገማዎች",
      ratingsCount: "ግምገማዎች",
      ratingLabel: "ደረጃ:",
      poor: "⭐ ደካማ",
      fair: "⭐⭐ መካከለኛ",
      good: "⭐⭐⭐ ጥሩ",
      veryGood: "⭐⭐⭐⭐ በጣም ጥሩ",
      excellent: "⭐⭐⭐⭐⭐ አስደናቂ",
      commentLabel: "አስተያየት:",
      commentPlaceholder: "ልምድዎን ያካፍሉ (አማራጭ)",
      submit: "ግምገማ ያስገቡ",
      submitting: "በማስገባት ላይ…",
      success: "ግምገማ በተሳካ ሁኔታ ቀርቧል!",
      errorLogin: "ግምገማ ለማስገባት እባክዎ ይግቡ",
      recentTitle: "የቅርብ ጊዜ ግምገማዎች",
      noReviews: "ምንም ግምገማ የለም",
      noComment: "አስተያየት የለም",
    },
    login: {
      title: "ግባ",
      emailPlaceholder: "ኢሜይል",
      passwordPlaceholder: "የሚስጥር ቃል",
      button: "ግባ",
      noAccount: "ሒሳብ የለዎትም?",
      registerLink: "እዚህ ይመዝገቡ",
      failed: "መግቢያ አልተሳካም",
    },
    register: {
      title: "ይመዝገቡ",
      namePlaceholder: "ሙሉ ስም",
      emailPlaceholder: "ኢሜይል",
      passwordPlaceholder: "የሚስጥር ቃል",
      button: "ይመዝገቡ",
      success: "ምዝገባ ተሳክቷል! ወደ መግቢያ ገጽ እየተላኩ ነው…",
      hasAccount: "ሒሳብ አለዎት?",
      loginLink: "እዚህ ይግቡ",
      failed: "ምዝገባ አልተሳካም",
    },
    analytics: {
      title: "📊 የትንታኔ ዳሽቦርድ",
      loading: "ትንታኔ በመጫን ላይ...",
      fetchFailed: "ትንታኔ ማምጣት አልተሳካም",
      totalBookings: "ጠቅላላ ቦኪንጎች",
      totalRevenue: "ጠቅላላ ገቢ",
      occupancyRate: "የወሰደ ደረጃ",
      statusBreakdown: "የቦኪንግ ሁኔታ ትንታኔ",
      refresh: "🔄 ዳታ አዘምን",
    },
    dashboard: {
      loading: "በመጫን ላይ...",
      loginRequired: "እባክዎ መጀመሪያ ይግቡ",
      fetchFailed: "ዳሽቦርድ ዳታ ማምጣት አልተሳካም",
      welcome: "እንኳን ደህና መጡ,",
      totalBookings: "ጠቅላላ ቦኪንጎች",
      activeOffers: "ንቁ ቅናሾች",
      occupancyRate: "የወሰደ ደረጃ",
      yourBookings: "የእርስዎ ቦኪንጎች",
      noBookings: "ቦኪንግ ገና የለም",
      bookingId: "ቦኪንግ መ.ቁ",
      checkIn: "ቼክ-ኢን",
      checkOut: "ቼክ-አውት",
      totalPrice: "ጠቅላላ ዋጋ",
      status: "ሁኔታ",
    },
    admin: {
      loginTitle: "🔑 የሠራተኛ ፖርታል",
      loginSubtitle: "ለተፈቀደ ሠራተኛ ብቻ",
      emailLabel: "ኢሜይል",
      passwordLabel: "የምስጢር ቃል",
      emailPlaceholder: "staff@hotel.com",
      loggingIn: "በመግባት ላይ...",
      login: "ግባ",
      demoAccounts: "የሙከራ መለያዎች:",
      accessDeniedLogin: "መዳረሻ ተከልክሏል። ለሠራተኞች ብቻ።",
      loginFailed: "መግባት አልተሳካም",
      loading: "በመጫን ላይ...",
      dashboardSubtitle: "የቦኪንግ አስተዳደር ስርዓት",
      adminRole: "አስተዳዳሪ",
      managerRole: "ማናጀር",
      receptionistRole: "ሪሲፕሽኒስት",
      dashboard: "ዳሽቦርድ",
      logout: "↪ ውጣ",
      totalBookings: "ጠቅላላ ቦኪንጎች",
      pending: "በመጠባበቅ ላይ",
      confirmed: "የተረጋገጠ",
      revenue: "ገቢ",
      listView: "☰ ዝርዝር እይታ",
      roomManagementTab: "🏨 የክፍል አስተዳደር",
      repeatCustomersTab: "🔄 ተደጋጋሚ ደንበኞች",
      paymentVerificationTab: "💳 የክፍያ ማረጋገጫ",
      offersTab: "🎁 ቅናሾች",
      searchPlaceholder: "በስም፣ ኢሜይል፣ ወይም ቦኪንግ መ.ቁ ፈልግ...",
      allStatus: "ሁሉም ሁኔታ",
      checkedIn: "ገብቷል",
      checkedOut: "ወጥቷል",
      cancelled: "ተሰርዟል",
      allReception: "ሁሉም ሪሴፕሽን",
      pendingDecision: "ውሳኔ በመጠባበቅ",
      approved: "ጸድቋል",
      rejected: "ውድቅ ሆኗል",
      bookingIdCol: "ቦኪንግ መ.ቁ",
      guestCol: "እንግዳ",
      roomCol: "ክፍል",
      datesCol: "ቀኖች",
      amountCol: "መጠን",
      statusCol: "ሁኔታ",
      paymentCol: "ክፍያ",
      receptionCol: "ሪሴፕሽን",
      verifiedByCol: "ያረጋገጠ",
      actionCol: "እርምጃ",
      noBookingsFound: "ለፍለጋዎ የሚዛመድ ቦኪንግ አልተገኘም።",
      guestFallback: "እንግዳ",
      roomPrefix: "ክፍል",
      paymentPending: "⏳ በመጠባበቅ",
      paymentVerified: "✅ ተረጋግጧል",
      paymentRejected: "❌ ውድቅ",
      receptionApproved: "✅ ጸድቋል",
      receptionRejected: "❌ ውድቅ ሆኗል",
      receptionPending: "⏳ በመጠባበቅ",
      decide: "⚖️ ወስን",
      override: "✏️ ሻር",
      roomMgmtTitle: "የክፍል አስተዳደር",
      addNewRoom: "+ አዲስ ክፍል ጨምር",
      roomMgmtAccessDenied: "የክፍል አስተዳደር ለአስተዳዳሪ እና ማናጀር ብቻ ነው።",
      imageCol: "ምስል",
      roomNumCol: "ክፍል ቁ.",
      typeCol: "አይነት",
      floorCol: "ፎቅ",
      bedCol: "አልጋ",
      maxGuestsCol: "ከፍተኛ እንግዶች",
      sizeCol: "ስፋት",
      actionsCol: "እርምጃዎች",
      editRoomTitle: "ክፍል አርትዕ",
      createRoomTitle: "አዲስ ክፍል ፍጠር",
      roomNameLabel: "የክፍል ስም",
      roomTypeLabel: "የክፍል አይነት",
      selectType: "አይነት ምረጥ",
      priceLabel: "ዋጋ/ሌሊት (ብር)",
      maxGuestsLabel: "👤 ከፍተኛ እንግዶች",
      roomSizeLabel: "የክፍል ስፋት",
      bedTypeLabel: "🛏 የአልጋ አይነት",
      descriptionLabel: "መግለጫ",
      floorLabel: "ፎቅ",
      statusLabel: "ሁኔታ",
      amenitiesLabel: "አገልግሎቶች",
      roomImagesLabel: "የክፍል ምስሎች",
      upTo3: "(እስከ 3)",
      noImagesYet: "ምስል ገና አልተጫነም",
      dropImages: "ምስሎችን እዚህ ጣል ወይም ጠቅ አድርጎ ጫን",
      slotsRemaining: "ቦታ ቀርቷል · JPG, PNG, WebP እስከ 5MB",
      roomNamePlaceholder: "ለምሳሌ: ዲሉክስ ኦሽን ስዊት",
      pricePlaceholder: "ለምሳሌ: 2500",
      sizePlaceholder: "42 ካ.ሜ",
      bedTypePlaceholder: "ኪንግ፣ ኩዊን፣ ትዊን...",
      descriptionPlaceholder: "ክፍሉን ይግለጹ...",
      floorPlaceholder: "1",
      statusAvailable: "ነጻ",
      statusOccupied: "ተይዟል",
      statusMaintenance: "ጥገና",
      cancel: "ሰርዝ",
      updateRoom: "ክፍል አዘምን",
      createRoom: "ክፍል ፍጠር",
      deleteConfirm: "ይህን ክፍል ይሰርዙ?",
      fetchFailed: "ዳታ ማምጣት አልተሳካም",
      verifyFailed: "ክፍያ ማረጋገጥ አልተሳካም",
      verifyFailedPrefix: "የክፍያ ማረጋገጫ አልተሳካም: ",
      decisionFailed: "ውሳኔ ማስገባት አልተሳካም",
      decisionFailedPrefix: "ውሳኔ አልተሳካም: ",
      deleteRoomFailed: "ክፍል መሰረዝ አልተሳካም",
      saveRoomFailed: "ክፍል ማስቀመጥ አልተሳካም",
      paymentVerificationTitle: "💳 የክፍያ ማረጋገጫ",
      paymentVerifySub: "የእንግዳ ክፍያ ቅጂዎችን ያረጋግጡ",
      awaitingVerification: "⏳ ማረጋገጫ በመጠባበቅ",
      noPendingProofs: "ያልተረጋገጠ ክፍያ ቅጂ የለም።",
      bookingPrefix: "ቦኪንግ #",
      viewFullImage: "ሙሉ ምስል ይመልከቱ",
      approvePayment: "✅ ክፍያ ፍቀዱ",
      rejectPayment: "❌ ውድቅ",
      verifiedSection: "✅ ተረጋግጧል",
      activeOffers: "ንቁ ቅናሾች",
      nameCol: "ስም",
      discountCol: "ቅናሽ",
      validFromCol: "ጀምሮ",
      validToCol: "እስከ",
      repeatCustomersTitle: "🔄 ተደጋጋሚ ደንበኞች",
      repeatCustomersSub: "2 ወይም ከዚያ በላይ ቦኪንግ ያደረጉ ደንበኞች",
      filterByName: "በስም አጣራ",
      filterByEmail: "በኢሜይል አጣራ",
      filterByPhone: "በስልክ አጣራ",
      namePlaceholder: "የደንበኛ ስም ያስገቡ...",
      emailFilterPlaceholder: "ኢሜይል አድራሻ ያስገቡ...",
      phoneFilterPlaceholder: "ስልክ ቁጥር ያስገቡ...",
      clearFilters: "ማጣሪያ አጽዳ",
      customerNameCol: "የደንበኛ ስም",
      emailCol: "ኢሜይል",
      phoneCol: "ስልክ",
      totalBookingsCol: "ጠቅላላ ቦኪንጎች",
      totalSpentCol: "ጠቅላላ ወጪ",
      firstBookingCol: "የመጀመሪያ ቦኪንግ",
      lastBookingCol: "የመጨረሻ ቦኪንግ",
      noRepeatCustomers: "ተደጋጋሚ ደንበኛ አልተገኘም።",
      unknownName: "ያልታወቀ",
      naPhone: "የለም",
      repeatCustomersAccessDenied: "ተደጋጋሚ ደንበኞች ለአስተዳዳሪ እና ሪሲፕሽኒስት ብቻ ነው።",
      overrideDecision: "ውሳኔ ሻር",
      bookingDecision: "የቦኪንግ ውሳኔ",
      guestLabel: "እንግዳ:",
      roomLabel: "ክፍል:",
      datesLabel: "ቀኖች:",
      amountLabel: "መጠን:",
      previouslyApprovedBy: "ቀደም ሲል ጸድቆ የጸደቀው",
      previouslyRejectedBy: "ቀደም ሲል ውድቅ ያደረገው",
      onDate: "ቀን",
      decisionLabel: "ውሳኔ:",
      approveBtn: "✅ ፍቀድ",
      rejectBtn: "❌ ውድቅ",
      notesOptional: "ማስታወሻ (አማራጭ):",
      notesLabel: "ማስታወሻ:",
      notesPlaceholder: "ማናቸውም ተጨማሪ ማስታወሻ ያስገቡ...",
      submitting: "በማስገባት ላይ...",
      submitDecision: "ውሳኔ አስገባ",
      loyaltyDiscount: "ታማኝነት",
      loyaltyDiscountApplied: "ታማኝነት ቅናሽ ተተግብሯል",
      accessDeniedTitle: "መዳረሻ ተከልክሏል",
    },
  },
};

function getNestedValue(source, key) {
  return key.split(".").reduce((value, segment) => {
    if (value && Object.prototype.hasOwnProperty.call(value, segment)) {
      return value[segment];
    }
    return undefined;
  }, source);
}

const LanguageContext = createContext({
  language: DEFAULT_LANGUAGE,
  setLanguage: () => {},
  toggleLanguage: () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(
    localStorage.getItem("language") || DEFAULT_LANGUAGE,
  );

  useEffect(() => {
    localStorage.setItem("language", language);
    document.documentElement.lang = language;
  }, [language]);

  const value = useMemo(() => {
    const t = (key) => {
      const activeTranslations =
        translations[language] || translations[DEFAULT_LANGUAGE];
      return (
        getNestedValue(activeTranslations, key) ??
        getNestedValue(translations[DEFAULT_LANGUAGE], key) ??
        key
      );
    };

    return {
      language,
      setLanguage,
      toggleLanguage: () =>
        setLanguage((current) => (current === "en" ? "am" : "en")),
      t,
    };
  }, [language]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useI18n() {
  return useContext(LanguageContext);
}
